layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  # sort_by: pushed
  sort_by options:
     - pushed
     - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  orcid: 0000-0001-5684-2256
  google_scholar: Hcb6i0gAAAAJ
  linkedin: orionzhou
  github: orionzhou
  email: zhoupenggeni@gmail.com
  twitter: orionzhou
  # website: https://orionzhou.github.io

topics:
  - name: Python
    web_url: https://www.python.org
    icon_txt: fab fa-python
  - name: R
    web_url: https://www.python.org
    icon_txt: fab fa-r-project
  - name: High Performance Computing
    web_url: https://en.wikipedia.org/wiki/Supercomputer
    icon_txt: fas fa-server
  - name: Cloud Computing
    web_url: https://en.wikipedia.org/wiki/Cloud_computing
    icon_txt: fas fa-cloud
